---
title: "HW6_Continuous_time_process"
author: "Kiseok Lee"
date: "2022-02-26"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(fig.width=11, fig.height=9,
                      error=TRUE, echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE,
                      tidy.opts=list(width.cutoff=60),tidy=TRUE)
```

## HW6 Continuous time process
Name: **Kiseok Lee** \
Date: 2/26/22 \
Class: **HGEN 486 Computational Biology**


```{r, echo=FALSE}
# libraries
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(vegan)
library(tidyverse)
library(magrittr)
library(readxl)
library(reshape2)
library(gtools)
library(devtools)
library(openxlsx)
library(ape)
library(stringr)
library(tidyr)
library(ggrepel)
library(ggpubr)

## theme for ggplot
mytheme <- theme_bw() + 
  theme(text = element_text(family="serif")) +
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=10, family="serif"))+
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank(),panel.background=element_blank(),panel.border=element_blank(),plot.background=element_blank())+
  theme(axis.ticks = element_line(size = 1.1))

mytheme_2d <- theme_bw() + 
  theme(text = element_text(family="serif")) +
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=13, family="serif"))+
  # theme(panel.grid.major = element_blank()) +
  # theme(panel.grid.minor = element_blank(),panel.background=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))


# color collection
my_color_collection <- c(
  "#CBD588", "#5F7FC7", "orange", "#AD6F3B", "#673770", 
  "#D14285", "#652926", "#C84248", "#8569D5", "#5E738F",
  "#D1A33D", "#8A7C64", "#599861","#616163", "#FFCDB2",
  "#6D9F71", "#242F40",
  "#CCA43B", "#F92A82", "#ED7B84", "#7EB77F", 
  "#DEC4A1", "#E5D1D0", '#0E8482', '#C9DAEA', '#337357', 
  '#95C623', '#E55812', '#04471C', '#F2D7EE', '#D3BCC0', 
  '#A5668B', '#69306D', '#0E103D', '#1A535C', '#4ECDC4', 
  '#F7FFF7', '#FF6B6B', '#FFE66D', '#6699CC', '#FFF275', 
  '#FF8C42', '#FF3C38', '#A23E48', '#000000', '#CF5C36', 
  '#EEE5E9', '#7C7C7C', '#EFC88B', '#2E5266', '#6E8898', 
  '#9FB1BC', '#D3D0CB', '#E2C044', '#5BC0EB', '#FDE74C', 
  '#9BC53D', '#E55934', '#FA7921', "#CD9BCD", "#508578", "#DA5724")

# for git push, use this instead of using wflow_git_push()
# git push -u origin master (in the Git app / in the working directory)

# for making pdf file
library(rmarkdown)
# render("analysis/~~.Rmd", "pdf_document")

```

## 1. Basic molecular phylogenetics

## 1-b) Compute log-likelihood

```{r}

# f(t)
f_t <- function(time){
  mu = 0.2 * 10^(-8)
  return(1/4 * (1 - exp(-mu * time)))
}

# transition function
transition_prob <- function(from="A", to="G",time){
  if (from == to){
    return(1 - 3*f_t(time))
  } else{
    # if from != to
    return(f_t(time))
  }
}

# P G|G (t1)
transition_prob(from = "G", to= "G", time = 7*10^6)

# P X|G(t1 - t2) x P A|X (t2) ^2 
vec_nuc = c("A","T","G","C")

vec_prob = c()
for (i in vec_nuc){
  print(i)
  prob1 = transition_prob(from = "G", to= i, time = 1*10^6)
  print(prob1)
  prob2 = transition_prob(from = i, to= "A", time = 6*10^6)^2
  print(prob2)
  vec_prob = c(vec_prob, prob1*prob2)
}

vec_prob
sum(vec_prob)

# likelihood
transition_prob(from = "G", to= "G", time = 7*10^6) * sum(vec_prob)

# final answer(log-likelihood): log P(data | mu, t1, t2)
log(transition_prob(from = "G", to= "G", time = 7*10^6) * sum(vec_prob))
```
Answer: -7.612402


## 1-c) Compute log-likelihood

```{r}

# P A|G (t1)
transition_prob(from = "G", to= "A", time = 7*10^6)

# P X|G(t1 - t2) x P A|X (t2) ^2 
vec_nuc = c("A","T","G","C")

vec_prob_b = c()
for (i in vec_nuc){
  print(i)
  prob1 = transition_prob(from = "G", to= i, time = 1*10^6)
  print(prob1)
  prob2 = transition_prob(from = i, to= "A", time = 6*10^6) * transition_prob(from = i, to= "G", time = 6*10^6)
  print(prob2)
  vec_prob_b = c(vec_prob, prob1*prob2)
}

vec_prob_b
sum(vec_prob_b)

# likelihood
transition_prob(from = "G", to= "A", time = 7*10^6) * sum(vec_prob_b)

# final answer(log-likelihood): log P(data | mu, t1, t2)
log(transition_prob(from = "G", to= "A", time = 7*10^6) * sum(vec_prob_b))

```
Answer: -13.2639
